baseURL = 'https://matsko1506.github.io/'
locale = 'en-us'
title = 'matsko1506 blog'
theme = 'risotto'

[params.about]
 author = 'matsko1506'
 title = 'Polski blog o IT i cyberbezpieczeństwie''
 logo = '💻'

